### PR TITLE
L10n fr

### PR DESCRIPTION
**Pull request by tdd**
Hey again,

As mentioned in #17, this is the second step of our recent work on globalizing and localizing `lololodash`. This includes the commits referenced in #17, which will "disappear" when/if you merge that one first, to leave only FR-related commits for actual localization.

I remain, naturally, available for any discussion on this.

Looking forward to our getting that in,

Best,

### CODE REVIEW

**Comment by tdd** [comment]
Hey Martin! Thanks for the merges. Looking forward to a bumped version showing up on npm so our trainees can use it :smile:

**Comment by mdunisch** [comment]
Hi @tdd,

thank you for the translation and all the work you put into that! I'm really impressed - awesome!


Your right, the verify.js is not be the best solution we have at the moment - if you have any idea about improving just send a PR!

I did a npm publish a few seconds ago. Have fun at your nodeschool!

**Comment by tdd** [comment]
Hey Martin,

You're most welcome.  I'll be working on upgrading `workshopper` to account for this kind of need in the coming weeks; when we have a solution that fits your use case, I'll be sure to come back and get this rolling here.

Re: npm publish: that's odd, npmjs.com keeps looking at 0.4.5…  Is there some delay I should expect for it to show up?

**Comment by mdunisch** [comment]
Npmjs.com sometimes need a little bit to show the new versions. Now it works :-)

**Comment by tdd** [comment]
Yay :tada:

-- 
Christophe Porteneuve
tdd@tddsworld.com

**Pull request merged**
